import typing
from BaseClasses import Item, ItemClassification


class ItemData(typing.NamedTuple):
    id: typing.Optional[int]
    classification: ItemClassification

    def is_progression(self):
        return self.classification & ItemClassification.progression == ItemClassification.progression

    def is_trap(self):
        return self.classification & ItemClassification.trap == ItemClassification.trap

    def is_filler(self):
        return self.classification & ItemClassification.filler == ItemClassification.filler



class TheBindingOfIsaacRepentanceItem(Item):
    game: str = "The Binding of Isaac Repentance"


junk_items = {
    "Random Pickup": ItemData(78031, ItemClassification.filler),
    "Random Heart": ItemData(78032, ItemClassification.filler),
    "Random Coin": ItemData(78033, ItemClassification.filler),
    "Random Bomb": ItemData(78034, ItemClassification.filler),
    "Random Key": ItemData(78035, ItemClassification.filler),
    "Random Card": ItemData(78036, ItemClassification.filler),
    "Random Pill": ItemData(78037, ItemClassification.filler),
    "Random Chest": ItemData(78038, ItemClassification.filler),
    "Random Trinket": ItemData(78039, ItemClassification.filler),
}

trap_items = {
    "Troll Bomb Trap": ItemData(78772, ItemClassification.trap),
    "Teleport Trap": ItemData(78773, ItemClassification.trap),
    "Retro Vision Trap": ItemData(78774, ItemClassification.trap),
    "Curse Trap": ItemData(78775, ItemClassification.trap),
    "Paralysis Trap": ItemData(78776, ItemClassification.trap),
    "Wavy Cap Trap": ItemData(78777, ItemClassification.trap),
}

# 78000 - 78???
item_table = {
    # items (main)
    "Treasure Room Item": ItemData(78000, ItemClassification.progression),
    "Shop Item": ItemData(78001, ItemClassification.progression),
    "Boss Item": ItemData(78002, ItemClassification.progression),
    "Devil Deal Item": ItemData(78003, ItemClassification.progression),
    "Angle Deal Item": ItemData(78004, ItemClassification.progression),
    "Secret Room Item": ItemData(78005, ItemClassification.progression),
    "Library Item": ItemData(78006, ItemClassification.progression),
    "Curse Room Item": ItemData(78007, ItemClassification.progression),
    "Planetarium Item": ItemData(78008, ItemClassification.progression),
    # item (experimental)
    "Shell Game Item": ItemData(78009, ItemClassification.progression),
    "Golden Chest Item": ItemData(78010, ItemClassification.progression),
    "Red Chest Item": ItemData(78011, ItemClassification.progression),
    "Beggar Item": ItemData(78012, ItemClassification.progression),
    "Demon Baggar Item": ItemData(78013, ItemClassification.progression),
    "Key Master Item": ItemData(78014, ItemClassification.progression),
    "Battery Bum Item": ItemData(78015, ItemClassification.progression),
    "Mom's Chest Item": ItemData(78016, ItemClassification.progression),
    "Greed Treasure Room Item": ItemData(78017, ItemClassification.progression),
    "Greed Boss Item": ItemData(78018, ItemClassification.progression),
    "Greed Shop Item": ItemData(78019, ItemClassification.progression),
    "Greed Devil Deal Item": ItemData(78020, ItemClassification.progression),
    "Greed Angel Deal Item": ItemData(78021, ItemClassification.progression),
    "Greed Curse Room Item": ItemData(78022, ItemClassification.progression),
    "Greed Secret Room Item": ItemData(78023, ItemClassification.progression),
    "Crane Game Item": ItemData(78024, ItemClassification.progression),
    "Ultra Secret Room Item": ItemData(78025, ItemClassification.progression),
    "Bomb Bum Item": ItemData(78026, ItemClassification.progression),
    "Old Chest Item": ItemData(78027, ItemClassification.progression),
    "Baby Shop Item": ItemData(78028, ItemClassification.progression),
    "Wooden Chest Item": ItemData(78029, ItemClassification.progression),
    "Rotten Beggar Item": ItemData(78030, ItemClassification.progression),
    **junk_items,
    # all collectables -> for start inv
    "Sad Onion": ItemData(78040, ItemClassification.progression),
    "Inner Eye": ItemData(78041, ItemClassification.progression),
    "Spoon Bender": ItemData(78042, ItemClassification.progression),
    "Crickets Head": ItemData(78043, ItemClassification.progression),
    "My Reflection": ItemData(78044, ItemClassification.progression),
    "Number One": ItemData(78045, ItemClassification.progression),
    "Blood Of The Martyr": ItemData(78046, ItemClassification.progression),
    "Brother Bobby": ItemData(78047, ItemClassification.progression),
    "Skatole": ItemData(78048, ItemClassification.progression),
    "Halo Of Flies": ItemData(78049, ItemClassification.progression),
    "1up": ItemData(78050, ItemClassification.progression),
    # 78050 need alias One Up
    "Magic Mushroom": ItemData(78051, ItemClassification.progression),
    "Virus": ItemData(78052, ItemClassification.progression),
    "Roid Rage": ItemData(78053, ItemClassification.progression),
    "Heart": ItemData(78054, ItemClassification.progression),
    "Raw Liver": ItemData(78055, ItemClassification.progression),
    "Skeleton Key": ItemData(78056, ItemClassification.progression),
    "Dollar": ItemData(78057, ItemClassification.progression),
    "Boom": ItemData(78058, ItemClassification.progression),
    "Transcendence": ItemData(78059, ItemClassification.progression),
    "Compass": ItemData(78060, ItemClassification.progression),
    "Lunch": ItemData(78061, ItemClassification.progression),
    "Dinner": ItemData(78062, ItemClassification.progression),
    "Dessert": ItemData(78063, ItemClassification.progression),
    "Breakfast": ItemData(78064, ItemClassification.progression),
    "Rotten Meat": ItemData(78065, ItemClassification.progression),
    "Wooden Spoon": ItemData(78066, ItemClassification.progression),
    "Belt": ItemData(78067, ItemClassification.progression),
    "Moms Underwear": ItemData(78068, ItemClassification.progression),
    "Moms Heels": ItemData(78069, ItemClassification.progression),
    "Moms Lipstick": ItemData(78070, ItemClassification.progression),
    "Wire Coat Hanger": ItemData(78071, ItemClassification.progression),
    "Bible": ItemData(78072, ItemClassification.progression),
    "Book Of Belial": ItemData(78073, ItemClassification.progression),
    "Necronomicon": ItemData(78074, ItemClassification.progression),
    "Poop": ItemData(78075, ItemClassification.progression),
    "Mr Boom": ItemData(78076, ItemClassification.progression),
    "Tammys Head": ItemData(78077, ItemClassification.progression),
    "Moms Bra": ItemData(78078, ItemClassification.progression),
    "Kamikaze": ItemData(78079, ItemClassification.progression),
    "Moms Pad": ItemData(78080, ItemClassification.progression),
    "Bobs Rotten Head": ItemData(78081, ItemClassification.progression),
    # "Pills Here": ItemData(78082, ItemClassification.progression), #doesn't exist
    "Teleport": ItemData(78083, ItemClassification.progression),
    "Yum Heart": ItemData(78084, ItemClassification.progression),
    "Lucky Foot": ItemData(78085, ItemClassification.progression),
    "Doctors Remote": ItemData(78086, ItemClassification.progression),
    "Cupids Arrow": ItemData(78087, ItemClassification.progression),
    "Shoop Da Whoop": ItemData(78088, ItemClassification.progression),
    "Steven": ItemData(78089, ItemClassification.progression),
    "Pentagram": ItemData(78090, ItemClassification.progression),
    "Dr Fetus": ItemData(78091, ItemClassification.progression),
    "Magneto": ItemData(78092, ItemClassification.progression),
    "Treasure Map": ItemData(78093, ItemClassification.progression),
    "Moms Eye": ItemData(78094, ItemClassification.progression),
    "Lemon Mishap": ItemData(78095, ItemClassification.progression),
    "Distant Admiration": ItemData(78096, ItemClassification.progression),
    "Book Of Shadows": ItemData(78097, ItemClassification.progression),
    "Book Of Belial Passive": ItemData(78098, ItemClassification.progression),
    "Ladder": ItemData(78099, ItemClassification.progression),
    # "Tarot Card": ItemData(78100, ItemClassification.progression), # doesn't exist
    "Charm Vampire": ItemData(78101, ItemClassification.progression),
    "Battery": ItemData(78102, ItemClassification.progression),
    "Steam Sale": ItemData(78103, ItemClassification.progression),
    "Anarchist Cookbook": ItemData(78104, ItemClassification.progression),
    "Hourglass": ItemData(78105, ItemClassification.progression),
    "Sister Maggy": ItemData(78106, ItemClassification.progression),
    "Technology": ItemData(78107, ItemClassification.progression),
    "Chocolate Milk": ItemData(78108, ItemClassification.progression),
    "Growth Hormones": ItemData(78109, ItemClassification.progression),
    "Mini Mush": ItemData(78110, ItemClassification.progression),
    "Rosary": ItemData(78111, ItemClassification.progression),
    "Cube Of Meat": ItemData(78112, ItemClassification.progression),
    "Quarter": ItemData(78113, ItemClassification.progression),
    "Phd": ItemData(78114, ItemClassification.progression),
    "Xray Vision": ItemData(78115, ItemClassification.progression),
    "My Little Unicorn": ItemData(78116, ItemClassification.progression),
    "Book Of Revelations": ItemData(78117, ItemClassification.progression),
    "Mark": ItemData(78118, ItemClassification.progression),
    "Pact": ItemData(78119, ItemClassification.progression),
    "Dead Cat": ItemData(78120, ItemClassification.progression),
    "Lord Of The Pit": ItemData(78121, ItemClassification.progression),
    "The Nail": ItemData(78122, ItemClassification.progression),
    "We Need To Go Deeper": ItemData(78123, ItemClassification.progression),
    "Deck Of Cards": ItemData(78124, ItemClassification.progression),
    "Monstros Tooth": ItemData(78125, ItemClassification.progression),
    "Lokis Horns": ItemData(78126, ItemClassification.progression),
    "Little Chubby": ItemData(78127, ItemClassification.progression),
    "Spider Bite": ItemData(78128, ItemClassification.progression),
    "Small Rock": ItemData(78129, ItemClassification.progression),
    "Spelunker Hat": ItemData(78130, ItemClassification.progression),
    "Super Bandage": ItemData(78131, ItemClassification.progression),
    "Gamekid": ItemData(78132, ItemClassification.progression),
    "Sack Of Pennies": ItemData(78133, ItemClassification.progression),
    "Robo Baby": ItemData(78134, ItemClassification.progression),
    "Little Chad": ItemData(78135, ItemClassification.progression),
    "Book Of Sin": ItemData(78136, ItemClassification.progression),
    "Relic": ItemData(78137, ItemClassification.progression),
    "Little Gish": ItemData(78138, ItemClassification.progression),
    "Little Steven": ItemData(78139, ItemClassification.progression),
    "Halo": ItemData(78140, ItemClassification.progression),
    "Moms Bottle Of Pills": ItemData(78141, ItemClassification.progression),
    "Common Cold": ItemData(78142, ItemClassification.progression),
    "Parasite": ItemData(78143, ItemClassification.progression),
    "D6": ItemData(78144, ItemClassification.progression),
    "Mr Mega": ItemData(78145, ItemClassification.progression),
    "Pinking Shears": ItemData(78146, ItemClassification.progression),
    "Wafer": ItemData(78147, ItemClassification.progression),
    "Money Equals Power": ItemData(78148, ItemClassification.progression),
    "Moms Contacts": ItemData(78149, ItemClassification.progression),
    "Bean": ItemData(78150, ItemClassification.progression),
    "Guardian Angel": ItemData(78151, ItemClassification.progression),
    "Demon Baby": ItemData(78152, ItemClassification.progression),
    "Moms Knife": ItemData(78153, ItemClassification.progression),
    "Ouija Board": ItemData(78154, ItemClassification.progression),
    "9 Volt": ItemData(78155, ItemClassification.progression),
    # 78155 need alias Nine Volt
    "Dead Bird": ItemData(78156, ItemClassification.progression),
    "Brimstone": ItemData(78157, ItemClassification.progression),
    "Blood Bag": ItemData(78158, ItemClassification.progression),
    "Odd Mushroom Thin": ItemData(78159, ItemClassification.progression),
    "Odd Mushroom Large": ItemData(78160, ItemClassification.progression),
    "Whore Of Babylon": ItemData(78161, ItemClassification.progression),
    "Monster Manual": ItemData(78162, ItemClassification.progression),
    "Dead Sea Scrolls": ItemData(78163, ItemClassification.progression),
    "Bobby Bomb": ItemData(78164, ItemClassification.progression),
    "Razor Blade": ItemData(78165, ItemClassification.progression),
    "Forget Me Now": ItemData(78166, ItemClassification.progression),
    "Forever Alone": ItemData(78167, ItemClassification.progression),
    "Bucket Of Lard": ItemData(78168, ItemClassification.progression),
    "Pony": ItemData(78169, ItemClassification.progression),
    "Bomb Bag": ItemData(78170, ItemClassification.progression),
    "Lump Of Coal": ItemData(78171, ItemClassification.progression),
    "Guppys Paw": ItemData(78172, ItemClassification.progression),
    "Guppys Tail": ItemData(78173, ItemClassification.progression),
    "Iv Bag": ItemData(78174, ItemClassification.progression),
    "Best Friend": ItemData(78175, ItemClassification.progression),
    "Remote Detonator": ItemData(78176, ItemClassification.progression),
    "Stigmata": ItemData(78177, ItemClassification.progression),
    "Moms Purse": ItemData(78178, ItemClassification.progression),
    "Bobs Curse": ItemData(78179, ItemClassification.progression),
    "Pageant Boy": ItemData(78180, ItemClassification.progression),
    "Scapular": ItemData(78181, ItemClassification.progression),
    "Speed Ball": ItemData(78182, ItemClassification.progression),
    "Bum Friend": ItemData(78183, ItemClassification.progression),
    "Guppys Head": ItemData(78184, ItemClassification.progression),
    "Prayer Card": ItemData(78185, ItemClassification.progression),
    "Notched Axe": ItemData(78186, ItemClassification.progression),
    "Infestation": ItemData(78187, ItemClassification.progression),
    "Ipecac": ItemData(78188, ItemClassification.progression),
    "Tough Love": ItemData(78189, ItemClassification.progression),
    "Mulligan": ItemData(78190, ItemClassification.progression),
    "Technology 2": ItemData(78191, ItemClassification.progression),
    "Mutant Spider": ItemData(78192, ItemClassification.progression),
    "Chemical Peel": ItemData(78193, ItemClassification.progression),
    "Peeper": ItemData(78194, ItemClassification.progression),
    "Habit": ItemData(78195, ItemClassification.progression),
    "Bloody Lust": ItemData(78196, ItemClassification.progression),
    "Crystal Ball": ItemData(78197, ItemClassification.progression),
    "Spirit Of The Night": ItemData(78198, ItemClassification.progression),
    "Crack The Sky": ItemData(78199, ItemClassification.progression),
    "Ankh": ItemData(78200, ItemClassification.progression),
    "Celtic Cross": ItemData(78201, ItemClassification.progression),
    "Ghost Baby": ItemData(78202, ItemClassification.progression),
    "Candle": ItemData(78203, ItemClassification.progression),
    "Cat O Nine Tails": ItemData(78204, ItemClassification.progression),
    "D20": ItemData(78205, ItemClassification.progression),
    "Harlequin Baby": ItemData(78206, ItemClassification.progression),
    "Epic Fetus": ItemData(78207, ItemClassification.progression),
    "Polyphemus": ItemData(78208, ItemClassification.progression),
    "Daddy Longlegs": ItemData(78209, ItemClassification.progression),
    "Spider Butt": ItemData(78210, ItemClassification.progression),
    "Sacrificial Dagger": ItemData(78211, ItemClassification.progression),
    "Mitre": ItemData(78212, ItemClassification.progression),
    "Rainbow Baby": ItemData(78213, ItemClassification.progression),
    "Dads Key": ItemData(78214, ItemClassification.progression),
    "Stem Cells": ItemData(78215, ItemClassification.progression),
    "Portable Slot": ItemData(78216, ItemClassification.progression),
    "Holy Water": ItemData(78217, ItemClassification.progression),
    "Fate": ItemData(78218, ItemClassification.progression),
    "Black Bean": ItemData(78219, ItemClassification.progression),
    "White Pony": ItemData(78220, ItemClassification.progression),
    "Sacred Heart": ItemData(78221, ItemClassification.progression),
    "Tooth Picks": ItemData(78222, ItemClassification.progression),
    "Holy Grail": ItemData(78223, ItemClassification.progression),
    "Dead Dove": ItemData(78224, ItemClassification.progression),
    "Blood Rights": ItemData(78225, ItemClassification.progression),
    "Guppys Hairball": ItemData(78226, ItemClassification.progression),
    "Abel": ItemData(78227, ItemClassification.progression),
    "Smb Super Fan": ItemData(78228, ItemClassification.progression),
    "Pyro": ItemData(78229, ItemClassification.progression),
    "3 Dollar Bill": ItemData(78230, ItemClassification.progression),
    "Telepathy Book": ItemData(78231, ItemClassification.progression),
    "Meat": ItemData(78232, ItemClassification.progression),
    "Magic 8 Ball": ItemData(78233, ItemClassification.progression),
    "Moms Coin Purse": ItemData(78234, ItemClassification.progression),
    "Squeezy": ItemData(78235, ItemClassification.progression),
    "Jesus Juice": ItemData(78236, ItemClassification.progression),
    "Box": ItemData(78237, ItemClassification.progression),
    "Moms Key": ItemData(78238, ItemClassification.progression),
    "Moms Eyeshadow": ItemData(78239, ItemClassification.progression),
    "Iron Bar": ItemData(78240, ItemClassification.progression),
    "Midas Touch": ItemData(78241, ItemClassification.progression),
    "Humbleing Bundle": ItemData(78242, ItemClassification.progression),
    "Fanny Pack": ItemData(78243, ItemClassification.progression),
    "Sharp Plug": ItemData(78244, ItemClassification.progression),
    "Guillotine": ItemData(78245, ItemClassification.progression),
    "Ball Of Bandages": ItemData(78246, ItemClassification.progression),
    "Champion Belt": ItemData(78247, ItemClassification.progression),
    "Butt Bombs": ItemData(78248, ItemClassification.progression),
    "Gnawed Leaf": ItemData(78249, ItemClassification.progression),
    "Spiderbaby": ItemData(78250, ItemClassification.progression),
    "Guppys Collar": ItemData(78251, ItemClassification.progression),
    "Lost Contact": ItemData(78252, ItemClassification.progression),
    "Anemic": ItemData(78253, ItemClassification.progression),
    "Goat Head": ItemData(78254, ItemClassification.progression),
    "Ceremonial Robes": ItemData(78255, ItemClassification.progression),
    "Moms Wig": ItemData(78256, ItemClassification.progression),
    "Placenta": ItemData(78257, ItemClassification.progression),
    "Old Bandage": ItemData(78258, ItemClassification.progression),
    "Sad Bombs": ItemData(78259, ItemClassification.progression),
    "Rubber Cement": ItemData(78260, ItemClassification.progression),
    "Anti Gravity": ItemData(78261, ItemClassification.progression),
    "Pyromaniac": ItemData(78262, ItemClassification.progression),
    "Crickets Body": ItemData(78263, ItemClassification.progression),
    "Gimpy": ItemData(78264, ItemClassification.progression),
    "Black Lotus": ItemData(78265, ItemClassification.progression),
    "Piggy Bank": ItemData(78266, ItemClassification.progression),
    "Moms Perfume": ItemData(78267, ItemClassification.progression),
    "Monstros Lung": ItemData(78268, ItemClassification.progression),
    "Abaddon": ItemData(78269, ItemClassification.progression),
    "Ball Of Tar": ItemData(78270, ItemClassification.progression),
    "Stop Watch": ItemData(78271, ItemClassification.progression),
    "Tiny Planet": ItemData(78272, ItemClassification.progression),
    "Infestation 2": ItemData(78273, ItemClassification.progression),
    # "235": ItemData(78274, ItemClassification.progression), #doesn't exist
    "E Coli": ItemData(78275, ItemClassification.progression),
    "Deaths Touch": ItemData(78276, ItemClassification.progression),
    "Key Piece 1": ItemData(78277, ItemClassification.progression),
    "Key Piece 2": ItemData(78278, ItemClassification.progression),
    "Experimental Treatment": ItemData(78279, ItemClassification.progression),
    "Contract From Below": ItemData(78280, ItemClassification.progression),
    "Infamy": ItemData(78281, ItemClassification.progression),
    "Trinity Shield": ItemData(78282, ItemClassification.progression),
    "Tech 5": ItemData(78283, ItemClassification.progression),
    "20 20": ItemData(78284, ItemClassification.progression),
    "Blue Map": ItemData(78285, ItemClassification.progression),
    "Bffs": ItemData(78286, ItemClassification.progression),
    "Hive Mind": ItemData(78287, ItemClassification.progression),
    "Theres Options": ItemData(78288, ItemClassification.progression),
    "Bogo Bombs": ItemData(78289, ItemClassification.progression),
    "Starter Deck": ItemData(78290, ItemClassification.progression),
    "Little Baggy": ItemData(78291, ItemClassification.progression),
    "Magic Scab": ItemData(78292, ItemClassification.progression),
    "Blood Clot": ItemData(78293, ItemClassification.progression),
    "Screw": ItemData(78294, ItemClassification.progression),
    "Hot Bombs": ItemData(78295, ItemClassification.progression),
    "Fire Mind": ItemData(78296, ItemClassification.progression),
    "Missing No": ItemData(78297, ItemClassification.progression),
    "Dark Matter": ItemData(78298, ItemClassification.progression),
    "Black Candle": ItemData(78299, ItemClassification.progression),
    "Proptosis": ItemData(78300, ItemClassification.progression),
    "Missing Page 2": ItemData(78301, ItemClassification.progression),
    "Clear Rune": ItemData(78302, ItemClassification.progression),
    "Smart Fly": ItemData(78303, ItemClassification.progression),
    "Dry Baby": ItemData(78304, ItemClassification.progression),
    "Juicy Sack": ItemData(78305, ItemClassification.progression),
    "Robo Baby 2": ItemData(78306, ItemClassification.progression),
    "Rotten Baby": ItemData(78307, ItemClassification.progression),
    "Headless Baby": ItemData(78308, ItemClassification.progression),
    "Leech": ItemData(78309, ItemClassification.progression),
    "Mystery Sack": ItemData(78310, ItemClassification.progression),
    "Bbf": ItemData(78311, ItemClassification.progression),
    "Bobs Brain": ItemData(78312, ItemClassification.progression),
    "Best Bud": ItemData(78313, ItemClassification.progression),
    "Lil Brimstone": ItemData(78314, ItemClassification.progression),
    "Isaacs Heart": ItemData(78315, ItemClassification.progression),
    "Lil Haunt": ItemData(78316, ItemClassification.progression),
    "Dark Bum": ItemData(78317, ItemClassification.progression),
    "Big Fan": ItemData(78318, ItemClassification.progression),
    "Sissy Longlegs": ItemData(78319, ItemClassification.progression),
    "Punching Bag": ItemData(78320, ItemClassification.progression),
    "How To Jump": ItemData(78321, ItemClassification.progression),
    "D100": ItemData(78322, ItemClassification.progression),
    "D4": ItemData(78323, ItemClassification.progression),
    "D10": ItemData(78324, ItemClassification.progression),
    "Blank Card": ItemData(78325, ItemClassification.progression),
    "Book Of Secrets": ItemData(78326, ItemClassification.progression),
    "Box Of Spiders": ItemData(78327, ItemClassification.progression),
    "Red Candle": ItemData(78328, ItemClassification.progression),
    "The Jar": ItemData(78329, ItemClassification.progression),
    "Flush": ItemData(78330, ItemClassification.progression),
    "Satanic Bible": ItemData(78331, ItemClassification.progression),
    "Head Of Krampus": ItemData(78332, ItemClassification.progression),
    "Butter Bean": ItemData(78333, ItemClassification.progression),
    "Magic Fingers": ItemData(78334, ItemClassification.progression),
    "Converter": ItemData(78335, ItemClassification.progression),
    "Blue Box": ItemData(78336, ItemClassification.progression),
    "Unicorn Stump": ItemData(78337, ItemClassification.progression),
    "Taurus": ItemData(78338, ItemClassification.progression),
    "Aries": ItemData(78339, ItemClassification.progression),
    "Cancer": ItemData(78340, ItemClassification.progression),
    "Leo": ItemData(78341, ItemClassification.progression),
    "Virgo": ItemData(78342, ItemClassification.progression),
    "Libra": ItemData(78343, ItemClassification.progression),
    "Scorpio": ItemData(78344, ItemClassification.progression),
    "Sagittarius": ItemData(78345, ItemClassification.progression),
    "Capricorn": ItemData(78346, ItemClassification.progression),
    "Aquarius": ItemData(78347, ItemClassification.progression),
    "Pisces": ItemData(78348, ItemClassification.progression),
    "Eves Mascara": ItemData(78349, ItemClassification.progression),
    "Judas Shadow": ItemData(78350, ItemClassification.progression),
    "Maggys Bow": ItemData(78351, ItemClassification.progression),
    "Holy Mantle": ItemData(78352, ItemClassification.progression),
    "Thunder Thighs": ItemData(78353, ItemClassification.progression),
    "Strange Attractor": ItemData(78354, ItemClassification.progression),
    "Cursed Eye": ItemData(78355, ItemClassification.progression),
    "Mysterious Liquid": ItemData(78356, ItemClassification.progression),
    "Gemini": ItemData(78357, ItemClassification.progression),
    "Cains Other Eye": ItemData(78358, ItemClassification.progression),
    "Blue Babys Only Friend": ItemData(78359, ItemClassification.progression),
    "Samsons Chains": ItemData(78360, ItemClassification.progression),
    "Mongo Baby": ItemData(78361, ItemClassification.progression),
    "Isaacs Tears": ItemData(78362, ItemClassification.progression),
    "Undefined": ItemData(78363, ItemClassification.progression),
    "Scissors": ItemData(78364, ItemClassification.progression),
    "Breath Of Life": ItemData(78365, ItemClassification.progression),
    "Polaroid": ItemData(78366, ItemClassification.progression),
    "Negative": ItemData(78367, ItemClassification.progression),
    "Ludovico Technique": ItemData(78368, ItemClassification.progression),
    "Soy Milk": ItemData(78369, ItemClassification.progression),
    "Godhead": ItemData(78370, ItemClassification.progression),
    "Lazarus Rags": ItemData(78371, ItemClassification.progression),
    "Mind": ItemData(78372, ItemClassification.progression),
    "Body": ItemData(78373, ItemClassification.progression),
    "Soul": ItemData(78374, ItemClassification.progression),
    "Dead Onion": ItemData(78375, ItemClassification.progression),
    "Broken Watch": ItemData(78376, ItemClassification.progression),
    "Boomerang": ItemData(78377, ItemClassification.progression),
    "Safety Pin": ItemData(78378, ItemClassification.progression),
    "Caffeine Pill": ItemData(78379, ItemClassification.progression),
    "Torn Photo": ItemData(78380, ItemClassification.progression),
    "Blue Cap": ItemData(78381, ItemClassification.progression),
    "Latch Key": ItemData(78382, ItemClassification.progression),
    "Match Book": ItemData(78383, ItemClassification.progression),
    "Synthoil": ItemData(78384, ItemClassification.progression),
    "Snack": ItemData(78385, ItemClassification.progression),
    "Diplopia": ItemData(78386, ItemClassification.progression),
    "Placebo": ItemData(78387, ItemClassification.progression),
    "Wooden Nickel": ItemData(78388, ItemClassification.progression),
    "Toxic Shock": ItemData(78389, ItemClassification.progression),
    "Mega Bean": ItemData(78390, ItemClassification.progression),
    "Glass Cannon": ItemData(78391, ItemClassification.progression),
    "Bomber Boy": ItemData(78392, ItemClassification.progression),
    "Crack Jacks": ItemData(78393, ItemClassification.progression),
    "Moms Pearls": ItemData(78394, ItemClassification.progression),
    "Car Battery": ItemData(78395, ItemClassification.progression),
    "Box Of Friends": ItemData(78396, ItemClassification.progression),
    "The Wiz": ItemData(78397, ItemClassification.progression),
    "8 Inch Nails": ItemData(78398, ItemClassification.progression),
    "Incubus": ItemData(78399, ItemClassification.progression),
    "Fates Reward": ItemData(78400, ItemClassification.progression),
    "Lil Chest": ItemData(78401, ItemClassification.progression),
    "Sworn Protector": ItemData(78402, ItemClassification.progression),
    "Friend Zone": ItemData(78403, ItemClassification.progression),
    "Lost Fly": ItemData(78404, ItemClassification.progression),
    "Scatter Bombs": ItemData(78405, ItemClassification.progression),
    "Sticky Bombs": ItemData(78406, ItemClassification.progression),
    "Epiphora": ItemData(78407, ItemClassification.progression),
    "Continuum": ItemData(78408, ItemClassification.progression),
    "Mr Dolly": ItemData(78409, ItemClassification.progression),
    "Curse Of The Tower": ItemData(78410, ItemClassification.progression),
    "Charged Baby": ItemData(78411, ItemClassification.progression),
    "Dead Eye": ItemData(78412, ItemClassification.progression),
    "Holy Light": ItemData(78413, ItemClassification.progression),
    "Host Hat": ItemData(78414, ItemClassification.progression),
    "Restock": ItemData(78415, ItemClassification.progression),
    "Bursting Sack": ItemData(78416, ItemClassification.progression),
    "Number Two": ItemData(78417, ItemClassification.progression),
    "Pupula Duplex": ItemData(78418, ItemClassification.progression),
    "Pay To Play": ItemData(78419, ItemClassification.progression),
    "Edens Blessing": ItemData(78420, ItemClassification.progression),
    "Friend Ball": ItemData(78421, ItemClassification.progression),
    "Tear Detonator": ItemData(78422, ItemClassification.progression),
    "Lil Gurdy": ItemData(78423, ItemClassification.progression),
    "Bumbo": ItemData(78424, ItemClassification.progression),
    "D12": ItemData(78425, ItemClassification.progression),
    "Censer": ItemData(78426, ItemClassification.progression),
    "Key Bum": ItemData(78427, ItemClassification.progression),
    "Rune Bag": ItemData(78428, ItemClassification.progression),
    "Seraphim": ItemData(78429, ItemClassification.progression),
    "Betrayal": ItemData(78430, ItemClassification.progression),
    "Zodiac": ItemData(78431, ItemClassification.progression),
    "Serpents Kiss": ItemData(78432, ItemClassification.progression),
    "Marked": ItemData(78433, ItemClassification.progression),
    "Tech X": ItemData(78434, ItemClassification.progression),
    "Ventricle Razor": ItemData(78435, ItemClassification.progression),
    "Tractor Beam": ItemData(78436, ItemClassification.progression),
    "Gods Flesh": ItemData(78437, ItemClassification.progression),
    "Maw Of The Void": ItemData(78438, ItemClassification.progression),
    "Spear Of Destiny": ItemData(78439, ItemClassification.progression),
    "Explosivo": ItemData(78440, ItemClassification.progression),
    "Chaos": ItemData(78441, ItemClassification.progression),
    "Spider Mod": ItemData(78442, ItemClassification.progression),
    "Farting Baby": ItemData(78443, ItemClassification.progression),
    "Gb Bug": ItemData(78444, ItemClassification.progression),
    "D8": ItemData(78445, ItemClassification.progression),
    "Purity": ItemData(78446, ItemClassification.progression),
    "Athame": ItemData(78447, ItemClassification.progression),
    "Empty Vessel": ItemData(78448, ItemClassification.progression),
    "Evil Eye": ItemData(78449, ItemClassification.progression),
    "Lusty Blood": ItemData(78450, ItemClassification.progression),
    "Cambion Conception": ItemData(78451, ItemClassification.progression),
    "Immaculate Conception": ItemData(78452, ItemClassification.progression),
    "More Options": ItemData(78453, ItemClassification.progression),
    "Crown Of Light": ItemData(78454, ItemClassification.progression),
    "Deep Pockets": ItemData(78455, ItemClassification.progression),
    "Succubus": ItemData(78456, ItemClassification.progression),
    "Fruit Cake": ItemData(78457, ItemClassification.progression),
    "Teleport 2": ItemData(78458, ItemClassification.progression),
    "Black Powder": ItemData(78459, ItemClassification.progression),
    "Kidney Bean": ItemData(78460, ItemClassification.progression),
    "Glowing Hour Glass": ItemData(78461, ItemClassification.progression),
    "Circle Of Protection": ItemData(78462, ItemClassification.progression),
    "Sack Head": ItemData(78463, ItemClassification.progression),
    "Night Light": ItemData(78464, ItemClassification.progression),
    "Obsessed Fan": ItemData(78465, ItemClassification.progression),
    "Mine Crafter": ItemData(78466, ItemClassification.progression),
    "Pjs": ItemData(78467, ItemClassification.progression),
    "Head Of The Keeper": ItemData(78468, ItemClassification.progression),
    "Papa Fly": ItemData(78469, ItemClassification.progression),
    "Multidimensional Baby": ItemData(78470, ItemClassification.progression),
    "Glitter Bombs": ItemData(78471, ItemClassification.progression),
    "My Shadow": ItemData(78472, ItemClassification.progression),
    "Jar Of Flies": ItemData(78473, ItemClassification.progression),
    "Lil Loki": ItemData(78474, ItemClassification.progression),
    "Milk": ItemData(78475, ItemClassification.progression),
    "D7": ItemData(78476, ItemClassification.progression),
    "Binky": ItemData(78477, ItemClassification.progression),
    "Moms Box": ItemData(78478, ItemClassification.progression),
    "Kidney Stone": ItemData(78479, ItemClassification.progression),
    "Mega Blast": ItemData(78480, ItemClassification.progression),
    "Dark Princes Crown": ItemData(78481, ItemClassification.progression),
    "Apple": ItemData(78482, ItemClassification.progression),
    "Lead Pencil": ItemData(78483, ItemClassification.progression),
    "Dog Tooth": ItemData(78484, ItemClassification.progression),
    "Dead Tooth": ItemData(78485, ItemClassification.progression),
    "Linger Bean": ItemData(78486, ItemClassification.progression),
    "Shard Of Glass": ItemData(78487, ItemClassification.progression),
    "Metal Plate": ItemData(78488, ItemClassification.progression),
    "Eye Of Greed": ItemData(78489, ItemClassification.progression),
    "Tarot Cloth": ItemData(78490, ItemClassification.progression),
    "Varicose Veins": ItemData(78491, ItemClassification.progression),
    "Compound Fracture": ItemData(78492, ItemClassification.progression),
    "Polydactyly": ItemData(78493, ItemClassification.progression),
    "Dads Lost Coin": ItemData(78494, ItemClassification.progression),
    "Midnight Snack": ItemData(78495, ItemClassification.progression),
    "Cone Head": ItemData(78496, ItemClassification.progression),
    "Belly Button": ItemData(78497, ItemClassification.progression),
    "Sinus Infection": ItemData(78498, ItemClassification.progression),
    "Glaucoma": ItemData(78499, ItemClassification.progression),
    "Parasitoid": ItemData(78500, ItemClassification.progression),
    "Eye Of Belial": ItemData(78501, ItemClassification.progression),
    "Sulfuric Acid": ItemData(78502, ItemClassification.progression),
    "Glyph Of Balance": ItemData(78503, ItemClassification.progression),
    "Analog Stick": ItemData(78504, ItemClassification.progression),
    "Contagion": ItemData(78505, ItemClassification.progression),
    "Finger": ItemData(78506, ItemClassification.progression),
    "Shade": ItemData(78507, ItemClassification.progression),
    "Depression": ItemData(78508, ItemClassification.progression),
    "Hushy": ItemData(78509, ItemClassification.progression),
    "Lil Monstro": ItemData(78510, ItemClassification.progression),
    "King Baby": ItemData(78511, ItemClassification.progression),
    "Big Chubby": ItemData(78512, ItemClassification.progression),
    "Broken Glass Cannon": ItemData(78513, ItemClassification.progression),
    "Plan C": ItemData(78514, ItemClassification.progression),
    "D1": ItemData(78515, ItemClassification.progression),
    "Void": ItemData(78516, ItemClassification.progression),
    "Pause": ItemData(78517, ItemClassification.progression),
    "Smelter": ItemData(78518, ItemClassification.progression),
    "Compost": ItemData(78519, ItemClassification.progression),
    "Dataminer": ItemData(78520, ItemClassification.progression),
    "Clicker": ItemData(78521, ItemClassification.progression),
    "Mama Mega": ItemData(78522, ItemClassification.progression),
    "Wait What": ItemData(78523, ItemClassification.progression),
    "Crooked Penny": ItemData(78524, ItemClassification.progression),
    "Dull Razor": ItemData(78525, ItemClassification.progression),
    "Potato Peeler": ItemData(78526, ItemClassification.progression),
    "Metronome": ItemData(78527, ItemClassification.progression),
    "D Infinity": ItemData(78528, ItemClassification.progression),
    "Edens Soul": ItemData(78529, ItemClassification.progression),
    "Acid Baby": ItemData(78530, ItemClassification.progression),
    "Yo Listen": ItemData(78531, ItemClassification.progression),
    "Adrenaline": ItemData(78532, ItemClassification.progression),
    "Jacobs Ladder": ItemData(78533, ItemClassification.progression),
    "Ghost Pepper": ItemData(78534, ItemClassification.progression),
    "Euthanasia": ItemData(78535, ItemClassification.progression),
    "Camo Undies": ItemData(78536, ItemClassification.progression),
    "Duality": ItemData(78537, ItemClassification.progression),
    "Eucharist": ItemData(78538, ItemClassification.progression),
    "Sack Of Sacks": ItemData(78539, ItemClassification.progression),
    "Greeds Gullet": ItemData(78540, ItemClassification.progression),
    "Large Zit": ItemData(78541, ItemClassification.progression),
    "Little Horn": ItemData(78542, ItemClassification.progression),
    "Brown Nugget": ItemData(78543, ItemClassification.progression),
    "Poke Go": ItemData(78544, ItemClassification.progression),
    "Backstabber": ItemData(78545, ItemClassification.progression),
    "Sharp Straw": ItemData(78546, ItemClassification.progression),
    "Moms Razor": ItemData(78547, ItemClassification.progression),
    "Bloodshot Eye": ItemData(78548, ItemClassification.progression),
    "Delirious": ItemData(78549, ItemClassification.progression),
    "Angry Fly": ItemData(78550, ItemClassification.progression),
    "Black Hole": ItemData(78551, ItemClassification.progression),
    "Bozo": ItemData(78552, ItemClassification.progression),
    "Broken Modem": ItemData(78553, ItemClassification.progression),
    "Mystery Gift": ItemData(78554, ItemClassification.progression),
    "Sprinkler": ItemData(78555, ItemClassification.progression),
    "Fast Bombs": ItemData(78556, ItemClassification.progression),
    "Buddy In A Box": ItemData(78557, ItemClassification.progression),
    "Lil Delirium": ItemData(78558, ItemClassification.progression),
    "Jumper Cables": ItemData(78559, ItemClassification.progression),
    "Coupon": ItemData(78560, ItemClassification.progression),
    "Telekinesis": ItemData(78561, ItemClassification.progression),
    "Moving Box": ItemData(78562, ItemClassification.progression),
    "Technology Zero": ItemData(78563, ItemClassification.progression),
    "Leprosy": ItemData(78564, ItemClassification.progression),
    "7 Seals": ItemData(78565, ItemClassification.progression),
    "Mr Me": ItemData(78566, ItemClassification.progression),
    "Angelic Prism": ItemData(78567, ItemClassification.progression),
    "Pop": ItemData(78568, ItemClassification.progression),
    "Deaths List": ItemData(78569, ItemClassification.progression),
    "Haemolacria": ItemData(78570, ItemClassification.progression),
    "Lachryphagy": ItemData(78571, ItemClassification.progression),
    "Trisagion": ItemData(78572, ItemClassification.progression),
    "Schoolbag": ItemData(78573, ItemClassification.progression),
    "Blanket": ItemData(78574, ItemClassification.progression),
    "Sacrificial Altar": ItemData(78575, ItemClassification.progression),
    "Lil Spewer": ItemData(78576, ItemClassification.progression),
    "Marbles": ItemData(78577, ItemClassification.progression),
    "Mystery Egg": ItemData(78578, ItemClassification.progression),
    "Flat Stone": ItemData(78579, ItemClassification.progression),
    "Marrow": ItemData(78580, ItemClassification.progression),
    "Slipped Rib": ItemData(78581, ItemClassification.progression),
    "Hallowed Ground": ItemData(78582, ItemClassification.progression),
    "Pointy Rib": ItemData(78583, ItemClassification.progression),
    "Book Of The Dead": ItemData(78584, ItemClassification.progression),
    "Dads Ring": ItemData(78585, ItemClassification.progression),
    "Divorce Papers": ItemData(78586, ItemClassification.progression),
    "Jaw Bone": ItemData(78587, ItemClassification.progression),
    "Brittle Bones": ItemData(78588, ItemClassification.progression),
    "Broken Shovel 1": ItemData(78589, ItemClassification.progression),
    "Broken Shovel 2": ItemData(78590, ItemClassification.progression),
    "Moms Shovel": ItemData(78591, ItemClassification.progression),
    "Mucormycosis": ItemData(78592, ItemClassification.progression),
    "2spooky": ItemData(78593, ItemClassification.progression),
    "Golden Razor": ItemData(78594, ItemClassification.progression),
    "Sulfur": ItemData(78595, ItemClassification.progression),
    "Fortune Cookie": ItemData(78596, ItemClassification.progression),
    "Eye Sore": ItemData(78597, ItemClassification.progression),
    "120 Volt": ItemData(78598, ItemClassification.progression),
    "It Hurts": ItemData(78599, ItemClassification.progression),
    "Almond Milk": ItemData(78600, ItemClassification.progression),
    "Rock Bottom": ItemData(78601, ItemClassification.progression),
    "Nancy Bombs": ItemData(78602, ItemClassification.progression),
    "Bar Of Soap": ItemData(78603, ItemClassification.progression),
    "Blood Puppy": ItemData(78604, ItemClassification.progression),
    "Dream Catcher": ItemData(78605, ItemClassification.progression),
    "Paschal Candle": ItemData(78606, ItemClassification.progression),
    "Divine Intervention": ItemData(78607, ItemClassification.progression),
    "Blood Oath": ItemData(78608, ItemClassification.progression),
    "Playdough Cookie": ItemData(78609, ItemClassification.progression),
    "Socks": ItemData(78610, ItemClassification.progression),
    "Eye Of The Occult": ItemData(78611, ItemClassification.progression),
    "Immaculate Heart": ItemData(78612, ItemClassification.progression),
    "Monstrance": ItemData(78613, ItemClassification.progression),
    "Intruder": ItemData(78614, ItemClassification.progression),
    "Dirty Mind": ItemData(78615, ItemClassification.progression),
    "Damocles": ItemData(78616, ItemClassification.progression),
    "Free Lemonade": ItemData(78617, ItemClassification.progression),
    "Spirit Sword": ItemData(78618, ItemClassification.progression),
    "Red Key": ItemData(78619, ItemClassification.progression),
    "Psy Fly": ItemData(78620, ItemClassification.progression),
    "Wavy Cap": ItemData(78621, ItemClassification.progression),
    "Rocket In A Jar": ItemData(78622, ItemClassification.progression),
    "Book Of Virtues": ItemData(78623, ItemClassification.progression),
    "Alabaster Box": ItemData(78624, ItemClassification.progression),
    "Stairway": ItemData(78625, ItemClassification.progression),
    "Sol": ItemData(78627, ItemClassification.progression),
    "Luna": ItemData(78628, ItemClassification.progression),
    "Mercurius": ItemData(78629, ItemClassification.progression),
    "Venus": ItemData(78630, ItemClassification.progression),
    "Terra": ItemData(78631, ItemClassification.progression),
    "Mars": ItemData(78632, ItemClassification.progression),
    "Jupiter": ItemData(78633, ItemClassification.progression),
    "Saturnus": ItemData(78634, ItemClassification.progression),
    "Uranus": ItemData(78635, ItemClassification.progression),
    "Neptunus": ItemData(78636, ItemClassification.progression),
    "Pluto": ItemData(78637, ItemClassification.progression),
    "Voodoo Head": ItemData(78638, ItemClassification.progression),
    "Eye Drops": ItemData(78639, ItemClassification.progression),
    "Act Of Contrition": ItemData(78640, ItemClassification.progression),
    "Member Card": ItemData(78641, ItemClassification.progression),
    "Battery Pack": ItemData(78642, ItemClassification.progression),
    "Moms Bracelet": ItemData(78643, ItemClassification.progression),
    "Scooper": ItemData(78644, ItemClassification.progression),
    "Ocular Rift": ItemData(78645, ItemClassification.progression),
    "Boiled Baby": ItemData(78646, ItemClassification.progression),
    "Freezer Baby": ItemData(78647, ItemClassification.progression),
    "Eternal D6": ItemData(78648, ItemClassification.progression),
    "Bird Cage": ItemData(78649, ItemClassification.progression),
    "Larynx": ItemData(78650, ItemClassification.progression),
    "Lost Soul": ItemData(78651, ItemClassification.progression),
    "Blood Bombs": ItemData(78653, ItemClassification.progression),
    "Lil Dumpy": ItemData(78654, ItemClassification.progression),
    "Birds Eye": ItemData(78655, ItemClassification.progression),
    "Lodestone": ItemData(78656, ItemClassification.progression),
    "Rotten Tomato": ItemData(78657, ItemClassification.progression),
    "Birthright": ItemData(78658, ItemClassification.progression),
    "Red Stew": ItemData(78660, ItemClassification.progression),
    "Genesis": ItemData(78661, ItemClassification.progression),
    "Sharp Key": ItemData(78662, ItemClassification.progression),
    "Booster Pack": ItemData(78663, ItemClassification.progression),
    "Mega Mush": ItemData(78664, ItemClassification.progression),
    "Knife Piece 1": ItemData(78665, ItemClassification.progression),
    "Knife Piece 2": ItemData(78666, ItemClassification.progression),
    "Death Certificate": ItemData(78667, ItemClassification.progression),
    "Bot Fly": ItemData(78668, ItemClassification.progression),
    "Meat Cleaver": ItemData(78670, ItemClassification.progression),
    "Evil Charm": ItemData(78671, ItemClassification.progression),
    "Dogma": ItemData(78672, ItemClassification.progression),
    "Purgatory": ItemData(78673, ItemClassification.progression),
    "Stitches": ItemData(78674, ItemClassification.progression),
    "R Key": ItemData(78675, ItemClassification.progression),
    "Knockout Drops": ItemData(78676, ItemClassification.progression),
    "Eraser": ItemData(78677, ItemClassification.progression),
    "Yuck Heart": ItemData(78678, ItemClassification.progression),
    "Urn Of Souls": ItemData(78679, ItemClassification.progression),
    "Akeldama": ItemData(78680, ItemClassification.progression),
    "Magic Skin": ItemData(78681, ItemClassification.progression),
    "Revelation": ItemData(78682, ItemClassification.progression),
    "Consolation Prize": ItemData(78683, ItemClassification.progression),
    "Tinytoma": ItemData(78684, ItemClassification.progression),
    "Brimstone Bombs": ItemData(78685, ItemClassification.progression),
    "4 5 Volt": ItemData(78686, ItemClassification.progression),
    "Fruity Plum": ItemData(78688, ItemClassification.progression),
    "Plum Flute": ItemData(78689, ItemClassification.progression),
    "Star Of Bethlehem": ItemData(78690, ItemClassification.progression),
    "Cube Baby": ItemData(78691, ItemClassification.progression),
    "Vade Retro": ItemData(78692, ItemClassification.progression),
    "False Phd": ItemData(78693, ItemClassification.progression),
    "Spin To Win": ItemData(78694, ItemClassification.progression),
    "Damocles Passive": ItemData(78695, ItemClassification.progression),
    "Vasculitis": ItemData(78696, ItemClassification.progression),
    "Giant Cell": ItemData(78697, ItemClassification.progression),
    "Tropicamide": ItemData(78698, ItemClassification.progression),
    "Card Reading": ItemData(78699, ItemClassification.progression),
    "Quints": ItemData(78700, ItemClassification.progression),
    "Tooth And Nail": ItemData(78702, ItemClassification.progression),
    "Binge Eater": ItemData(78703, ItemClassification.progression),
    "Guppys Eye": ItemData(78704, ItemClassification.progression),
    "Straw Man": ItemData(78706, ItemClassification.progression),
    "Dads Note": ItemData(78707, ItemClassification.progression),
    "Sausage": ItemData(78708, ItemClassification.progression),
    "Options": ItemData(78709, ItemClassification.progression),
    "Candy Heart": ItemData(78710, ItemClassification.progression),
    "Pound Of Flesh": ItemData(78711, ItemClassification.progression),
    "Redemption": ItemData(78712, ItemClassification.progression),
    "Spirit Shackles": ItemData(78713, ItemClassification.progression),
    "Cracked Orb": ItemData(78714, ItemClassification.progression),
    "Empty Heart": ItemData(78715, ItemClassification.progression),
    "Astral Projection": ItemData(78716, ItemClassification.progression),
    "C Section": ItemData(78717, ItemClassification.progression),
    "Lil Abaddon": ItemData(78718, ItemClassification.progression),
    "Montezumas Revenge": ItemData(78719, ItemClassification.progression),
    "Lil Portal": ItemData(78720, ItemClassification.progression),
    "Worm Friend": ItemData(78721, ItemClassification.progression),
    "Bone Spurs": ItemData(78722, ItemClassification.progression),
    "Hungry Soul": ItemData(78723, ItemClassification.progression),
    "Jar Of Wisps": ItemData(78724, ItemClassification.progression),
    "Soul Locket": ItemData(78725, ItemClassification.progression),
    "Friend Finder": ItemData(78726, ItemClassification.progression),
    "Inner Child": ItemData(78727, ItemClassification.progression),
    "Glitched Crown": ItemData(78728, ItemClassification.progression),
    "Jelly Belly": ItemData(78729, ItemClassification.progression),
    "Sacred Orb": ItemData(78730, ItemClassification.progression),
    "Sanguine Bond": ItemData(78731, ItemClassification.progression),
    "Swarm": ItemData(78732, ItemClassification.progression),
    "Heartbreak": ItemData(78733, ItemClassification.progression),
    "Bloody Gust": ItemData(78734, ItemClassification.progression),
    "Salvation": ItemData(78735, ItemClassification.progression),
    "Vanishing Twin": ItemData(78736, ItemClassification.progression),
    "Twisted Pair": ItemData(78737, ItemClassification.progression),
    "Azazels Rage": ItemData(78738, ItemClassification.progression),
    "Echo Chamber": ItemData(78739, ItemClassification.progression),
    "Isaacs Tomb": ItemData(78740, ItemClassification.progression),
    "Vengeful Spirit": ItemData(78741, ItemClassification.progression),
    "Esau Jr": ItemData(78742, ItemClassification.progression),
    "Berserk": ItemData(78743, ItemClassification.progression),
    "Dark Arts": ItemData(78744, ItemClassification.progression),
    "Abyss": ItemData(78745, ItemClassification.progression),
    "Supper": ItemData(78746, ItemClassification.progression),
    "Stapler": ItemData(78747, ItemClassification.progression),
    "Suplex": ItemData(78748, ItemClassification.progression),
    "Bag Of Crafting": ItemData(78749, ItemClassification.progression),
    "Flip": ItemData(78750, ItemClassification.progression),
    "Lemegeton": ItemData(78751, ItemClassification.progression),
    "Sumptorium": ItemData(78752, ItemClassification.progression),
    "Recall": ItemData(78753, ItemClassification.progression),
    "Hold": ItemData(78754, ItemClassification.progression),
    "Keepers Sack": ItemData(78755, ItemClassification.progression),
    "Keepers Kin": ItemData(78756, ItemClassification.progression),
    "Keepers Box": ItemData(78758, ItemClassification.progression),
    "Everything Jar": ItemData(78759, ItemClassification.progression),
    "Tmtrainer": ItemData(78760, ItemClassification.progression),
    "Anima Sola": ItemData(78761, ItemClassification.progression),
    "Spindown Dice": ItemData(78762, ItemClassification.progression),
    "Hypercoagulation": ItemData(78763, ItemClassification.progression),
    "Ibs": ItemData(78764, ItemClassification.progression),
    "Hemoptysis": ItemData(78765, ItemClassification.progression),
    "Ghost Bombs": ItemData(78766, ItemClassification.progression),
    "Gello": ItemData(78767, ItemClassification.progression),
    "Decap Attack": ItemData(78768, ItemClassification.progression),
    "Glass Eye": ItemData(78769, ItemClassification.progression),
    "Stye": ItemData(78770, ItemClassification.progression),
    "Moms Ring": ItemData(78771, ItemClassification.progression),
    **trap_items,
    # other
    "Victory": ItemData(None, ItemClassification.progression),
}

default_trap_items_weights = {
    "Troll Bomb Trap": 20,
    "Teleport Trap": 20,
    "Retro Vision Trap": 20,
    "Curse Trap": 20,
    "Paralysis Trap": 20,
    "Wavy Cap Trap": 20
}

default_junk_items_weights = {
    "Random Pickup": 0,
    "Random Heart": 5,
    "Random Coin": 6,
    "Random Bomb": 5,
    "Random Key": 5,
    "Random Card": 3,
    "Random Pill": 3,
    "Random Chest": 2,
    "Random Trinket": 1,
}

default_weights = {
    "Treasure Room Item": 10,
    "Shop Item": 10,
    "Boss Item": 8,
    "Devil Deal Item": 5,
    "Angle Deal Item": 5,
    "Secret Room Item": 6,
    "Library Item": 4,
    "Curse Room Item": 4,
    "Planetarium Item": 1,
    "Golden Chest Item": 6,
    "Red Chest Item": 6,
}

lookup_id_to_name: typing.Dict[int, str] = {data.id: name for name, data in item_table.items() if data.id}
